#include <stdio.h>

int main() {
	// Constants
	const double g = 9.80; // gravitational constant (m/s^2)
	const double efficiency = 0.9; // efficiency of conversion
	const double water_density = 1000.0; // kg per cubic meter

	// Variables
	double height, flow_rate;
	double power, work, mass;

	// Input
	printf("Enter the height of the dam in meters:");
	scanf("%lf", &height);

	printf("Enter the flow rate of water in cubic meters per second:");
	scanf("%lf", &flow_rate);

	// Mass of water flowing per second
	mass = flow_rate * water_density;

	// Work = m*g*h
	work = mass * g * height;

	// Power = n*Work
	power = efficiency * work;

	// Convert to megawatts (1 MW = 1,000,000 W)
	power = power / 1e6;

	// Output
	printf("Predicted power generated by the hydroelectric dam: %.2f megawatts\n", power);

	return 0;

} 	
